# Generated by Django 5.2.6 on 2025-10-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_directshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
